# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wredenba/Downloads/lc3tools-1.0.6

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wredenba/Downloads/lc3tools-1.0.6

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wredenba/Downloads/lc3tools-1.0.6/CMakeFiles /home/wredenba/Downloads/lc3tools-1.0.6/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wredenba/Downloads/lc3tools-1.0.6/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lc3core

# Build rule for target.
lc3core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lc3core
.PHONY : lc3core

# fast build rule for target.
lc3core/fast:
	$(MAKE) -f backend/CMakeFiles/lc3core.dir/build.make backend/CMakeFiles/lc3core.dir/build
.PHONY : lc3core/fast

#=============================================================================
# Target rules for targets named frontend_common

# Build rule for target.
frontend_common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 frontend_common
.PHONY : frontend_common

# fast build rule for target.
frontend_common/fast:
	$(MAKE) -f frontend/CMakeFiles/frontend_common.dir/build.make frontend/CMakeFiles/frontend_common.dir/build
.PHONY : frontend_common/fast

#=============================================================================
# Target rules for targets named simulator

# Build rule for target.
simulator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simulator
.PHONY : simulator

# fast build rule for target.
simulator/fast:
	$(MAKE) -f frontend/cli/CMakeFiles/simulator.dir/build.make frontend/cli/CMakeFiles/simulator.dir/build
.PHONY : simulator/fast

#=============================================================================
# Target rules for targets named assembler

# Build rule for target.
assembler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 assembler
.PHONY : assembler

# fast build rule for target.
assembler/fast:
	$(MAKE) -f frontend/cli/CMakeFiles/assembler.dir/build.make frontend/cli/CMakeFiles/assembler.dir/build
.PHONY : assembler/fast

#=============================================================================
# Target rules for targets named tutorial_grader

# Build rule for target.
tutorial_grader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tutorial_grader
.PHONY : tutorial_grader

# fast build rule for target.
tutorial_grader/fast:
	$(MAKE) -f frontend/grader/CMakeFiles/tutorial_grader.dir/build.make frontend/grader/CMakeFiles/tutorial_grader.dir/build
.PHONY : tutorial_grader/fast

#=============================================================================
# Target rules for targets named polyroot

# Build rule for target.
polyroot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 polyroot
.PHONY : polyroot

# fast build rule for target.
polyroot/fast:
	$(MAKE) -f frontend/grader/CMakeFiles/polyroot.dir/build.make frontend/grader/CMakeFiles/polyroot.dir/build
.PHONY : polyroot/fast

#=============================================================================
# Target rules for targets named interrupt

# Build rule for target.
interrupt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 interrupt
.PHONY : interrupt

# fast build rule for target.
interrupt/fast:
	$(MAKE) -f frontend/grader/CMakeFiles/interrupt.dir/build.make frontend/grader/CMakeFiles/interrupt.dir/build
.PHONY : interrupt/fast

#=============================================================================
# Target rules for targets named binsearch

# Build rule for target.
binsearch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 binsearch
.PHONY : binsearch

# fast build rule for target.
binsearch/fast:
	$(MAKE) -f frontend/grader/CMakeFiles/binsearch.dir/build.make frontend/grader/CMakeFiles/binsearch.dir/build
.PHONY : binsearch/fast

#=============================================================================
# Target rules for targets named pow2

# Build rule for target.
pow2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pow2
.PHONY : pow2

# fast build rule for target.
pow2/fast:
	$(MAKE) -f frontend/grader/CMakeFiles/pow2.dir/build.make frontend/grader/CMakeFiles/pow2.dir/build
.PHONY : pow2/fast

#=============================================================================
# Target rules for targets named grader_common

# Build rule for target.
grader_common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 grader_common
.PHONY : grader_common

# fast build rule for target.
grader_common/fast:
	$(MAKE) -f frontend/grader/CMakeFiles/grader_common.dir/build.make frontend/grader/CMakeFiles/grader_common.dir/build
.PHONY : grader_common/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... lc3core"
	@echo "... frontend_common"
	@echo "... simulator"
	@echo "... assembler"
	@echo "... tutorial_grader"
	@echo "... polyroot"
	@echo "... interrupt"
	@echo "... binsearch"
	@echo "... pow2"
	@echo "... grader_common"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

